language: c

compiler:
  - gcc

before_install:
  - sudo apt-get -qq update

install:
  - sudo apt-get install -qq gengetopt
  - sudo apt-get install -qq help2man

before_script:
  - autoreconf -vfi

script: 
  - ./configure --with-asm-backed-coroutines || (cat config.log; false)
  - make clean all check distcheck || (cat test/test-suite.log; false)

## whitelist
branches:
  only:
    - master
    - next

notifications:
  email:
    - devel@fresse.org
