language: c

sudo: false

os:
  - linux

compiler:
  - gcc-5

before_script:
  - autoreconf -vfi

env:
  - CONFOPTS="--enable-asm-backed-coroutines"
  - CONFOPTS="--disable-asm-backed-coroutines"

script: 
  - ./configure "${CONFOPTS}" || (cat config.log; false)
  - make clean all check distcheck || (cat test/test-suite.log; false)

## whitelist
branches:
  only:
    - master
    - next
    - /^v\d+\..*/

deploy:
  provider: releases
  api_key:
    secure: "SiSVINnjUURtKyRzK0vN7auhlL23Pl3UZKUts1EP8V39r2IkxYwYDPCKx8CFlcH/+qxwuY9FLQYN94gC1qT4FMskiPgwJW4cpqMAqiGt5Z3ZEBAMc0M9gqzPboi+ILqtYBoep0dYmNYYexuggdE5MxKukCEAoVyzFdALe2cYmZ8="
  file_glob: true
  file: truffle-*.tar.xz
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    - devel@fresse.org

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
